# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170109_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
