# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='img'),
        ),
    ]
