# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img', verbose_name='image'),
        ),
    ]
